// categories.js
export const categories = {
  "NỐI BẬT": [
    "Hàng Mỗi Về",
    "Độc quyền hội viên",
    "",
    "Optime",
    "Equipment",
    "Samba",
    "Gazetle",
    "Spezial",
    "SL 72",
    "Taekwondo",
    "Retro Icons",
    "Adizero",
    "Predator",
    "Bộ sưu tập T-Toe",
  ],
  GIẤY: [
    "Hàng mới về",
    "Originals",
    "Bóng đá",
    "Chạy bộ",
    "Tập",
    "Ngoài trời",
    "Bóng rố",
    "Dép & Dép xô ngôn",
    "Quần vợt",
    "Sportswear",
    "Giây sneaker đen",
    "Đánh gồm",
    "GIẤY “MUST-HAVE”",
    "",
  ],
  "QUẢN ÁO": [
    "Áo thun & Áo polo",
    "Áo Jersey",
    "Áo hoodie",
    "Bộ dồ thể thao",
    "Quần",
    "Quần bó",
    "Quần short",
    "Sportswear",
    "Áo khóác",
    "CO BÀN",
    "Tracksuits",
    "",
    "",
    "",
  ],
  "PHỤ KIỆN": [
    "Tất Cả Túi",
    "Tất",
    "Mũ Lưỡi Trai & Đội Đầu",
    "Găng Tay",
    "Ốp bảo vệ ống chân & Bắng buộc",
    "",
    "Ball",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  "THẾ THAO": [
    "Bóng đá",
    "Chạy",
    "Tập luyện",
    "Basketball",
    "Bơi lýi",
    "Đánh gồm",
    "Quần vợt",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  "ADIDAS SAMBA VỮA RA MẮT": [
    "",
    "MAKE YOUR SAMBA COUNT",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
};

// Hoặc dạng array để dễ map:
export const categoriesArray = Object.entries(categories).map(
  ([category, items]) => ({
    category,
    items: items.filter((item) => item.trim() !== ""), // Lọc các item trống
  })
);
