const provincesWithDistricts = {
  "Hà Nội": [
    "Quận Ba Đình",
    "Quận Hoàn Kiếm",
    "Quận Tây Hồ",
    "Quận Long Biên",
    "Quận Cầu Giấy",
    "Quận Đống Đa",
    "Quận Hai Bà Trưng",
    "Quận Hoàng Mai",
    "Quận Thanh Xuân",
    "Huyện Sóc Sơn",
    "Huyện Đông Anh",
    "Huyện Gia Lâm",
    "Quận Nam Từ Liêm",
    "Huyện Thanh Trì",
    "Quận Bắc Từ Liêm",
    "Huyện Mê Linh",
    "Quận Hà Đông",
    "Thị xã Sơn Tây",
    "Huyện Ba Vì",
    "Huyện Phúc Thọ",
    "Huyện Đan Phượng",
    "Huyện Hoài Đức",
    "Huyện Quốc Oai",
    "Huyện Thạch Thất",
    "Huyện Chương Mỹ",
    "Huyện Thanh Oai",
    "Huyện Thường Tín",
    "Huyện Phú Xuyên",
    "Huyện Ứng Hòa",
    "Huyện Mỹ Đức",
  ],
  "Thành phố Hồ Chí Minh": [
    "Quận 1",
    "Quận 3",
    "Quận 4",
    "Quận 5",
    "Quận 6",
    "Quận 7",
    "Quận 8",
    "Quận 10",
    "Quận 11",
    "Quận 12",
    "Quận Bình Tân",
    "Quận Bình Thạnh",
    "Quận Gò Vấp",
    "Quận Phú Nhuận",
    "Quận Tân Bình",
    "Quận Tân Phú",
    "Quận Thủ Đức",
    "Huyện Bình Chánh",
    "Huyện Cần Giờ",
    "Huyện Củ Chi",
    "Huyện Hóc Môn",
    "Huyện Nhà Bè",
  ],
  "Đà Nẵng": [
    "Quận Hải Châu",
    "Quận Thanh Khê",
    "Quận Sơn Trà",
    "Quận Ngũ Hành Sơn",
    "Quận Liên Chiểu",
    "Quận Cẩm Lệ",
    "Huyện Hòa Vang",
    "Huyện Hoàng Sa",
  ],
  // Thêm các tỉnh/thành phố khác cùng các quận/huyện tương ứng
};
export default provincesWithDistricts;
